from rest_framework import serializers

from core.models import CheckList, CheckListItem


class CheckListItemSerializer(serializers.ModelSerializer): 
    user = serializers.HiddenField(default=serializers.CurrentUserDefault())

    class Meta:
        model = CheckListItem
        fields = "__all__"

class CheckListSerializer(serializers.ModelSerializer):
    # here we are using nested serializer concept
    # this is to display the multiple items in the Checklist
    user = serializers.HiddenField(default=serializers.CurrentUserDefault())

    items = CheckListItemSerializer(source='checklistitem_set',many = True, read_only=True)
    #this 'checklistitem_set' is the default relational mapping generated by Django, when we link the item with a foreign key.
    class Meta:
        model = CheckList
        fields = "__all__"